### ISSUE TITLE
Broken triangulation

### ISSUE THREAD

**Issue by ColaColin** [brendankenny/libtess.js#16]
EDIT 2:

okay it seems the problem was that libtess generates a bunch of triangles with area zero. My code didn't like that very much and did stupid things.

So I guess this was my fault?

============

It appears that in some cases triangles outside the original bounds are created.

For example this polygon:

480 320 440 320 440 360 460 360 460 440 440 440 440 480 480 480 480 460 560 460 560 480 600 480 600 440 580 440 580 360 600 360 600 320 560 320 560 340 480 340

Looks like this:
https://i.imgur.com/rnJHSzp.png

libtess triangulation:
https://i.imgur.com/2MZsFIU.png

Earcut correctly triangulates:
https://i.imgur.com/4qsH4uf.png

This is one of multiple such examples I've encountered. Some were fixable by passing in the polyline in a reversed manner. This one however is not, it stays broken even when reversed. All examples had 90° angles and were basically build up from the union of multiple little squares.
Libtess manages to fix self intersections in the input, unlike earcut, which is great. But it seems it can generate self intersecting triangles on other inputs.

EDIT:
Another example is

500 320 460 320 460 420 360 420 360 460 460 460 460 560 500 560 500 460 600 460 600 420 500 420

The shape: https://i.imgur.com/nSYIqe5.png
The self intersecting triangulation: https://i.imgur.com/CGbuDf6.png

I am wondering if this is somehow my fault, but I can't see what I would be doing wrong

**Comment by brendankenny** [comment]
> okay it seems the problem was that libtess generates a bunch of triangles with area zero. My code didn't like that very much and did stupid things.

welll...it depends on your interpretation of reasonable output. Obviously zero-area triangles are less than ideal, but due to the way the algorithm triangulates, it uses zero-area triangles to keep the topology correct and avoid features like t-junctions. See this old [gamedev.net thread for some more details](https://www.gamedev.net/forums/topic/584914-polygon-tessellationtriangulation-implementations/?page=2&tab=comments#comment-4722121) (though sadly the old imageshack images are gone)
